name = "SymbolicIntegration"
uuid = "315ce56f-eed0-411d-ab8a-2fbdf9327b51"
authors = ["HaraldHofstaetter <hofi@harald-hofstaetter.at>", "Chris Rackauckas <accounts@chrisrackauckas.com>", "JuliaSymbolics contributors"]
version = "0.2.0"
description = "Symbolic integration algorithms for Julia"
repository = "https://github.com/JuliaSymbolics/SymbolicIntegration.jl"
license = "MIT"
keywords = ["symbolic", "integration", "mathematics", "computer-algebra"]

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"

[compat]
AbstractAlgebra = "0.46"
Nemo = "0.51"
SymbolicUtils = "3"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
